language: python

python:
  - "2.7"

env:
  - secure: "Ekkvjqo6LtpIMtg+6BmmCwfAHWB0TAQyRycHpKwmcALjU3K/OTzQzDCfUl3neakV12w+EQyxklAWpiqxjPqea/dA3qDvBWYxQ025oDfUz27p1DEOcdSA2dRzWCXNl1hm+rZCL2PcxTP0B91dBWrN4xOINc0rw5DEKW2wwuNuG9g="
  - DISPLAY=:99.0 MASTER=master_2.7.6_2.1.0.dev1773-afa28b9_rh5-64.sh RUNTIME=`pwd`/runtime

before_install:

  # Prepare a Python environment with enpkg installed in it.
  - wget https://s3.amazonaws.com/enstaller-assets/masters/rh5-64/2.7.6/$MASTER
  - bash $MASTER -bp $RUNTIME
  - source $RUNTIME/bin/activate
  - wget https://s3.amazonaws.com/enstaller-assets/enstaller/bootstrap.py
  - python `pwd`/bootstrap.py

  # At this point, enpkg is installed - provide auth info now.
  - echo "EPD_auth = '"${EPD_auth}"'" > ${HOME}/.enstaller4rc

  # Install pip
  - enpkg pip

  # Make sure you have a web browser installed (for the web tests) and the X
  # server is running
  - sudo apt-get update
  - sudo apt-get install firefox
  - sh -e /etc/init.d/xvfb start

install:
  - sh develop.sh

script:
  # Run the tests
  - nosetests -sv

after_script:
  - coverage report

notifications:
  email: false
