language: python

python:
  - "2.7"

env:
  - DISPLAY=:99.0

before_install:
  - echo "EPD_auth = 'dGVzdC5mcmVlQGZha2UuZG9tYWluOnRlc3Q9MTIzNA=='" > ${HOME}/.enstaller4rc
  - sh -e /etc/init.d/xvfb start

install:
  - pip install enstaller selenium
  - sudo apt-get install firefox
  - enpkg requirements.txt
  - enpkg optional_requirements.txt
  - python setup.py develop

script:
  - coverage run -m unittest discover

after_script:
  - coverage report

notifications:
  email: false
