language: python

python:
  - "2.7"

env:
  global:
    # EPD_auth
    - secure: "Ekkvjqo6LtpIMtg+6BmmCwfAHWB0TAQyRycHpKwmcALjU3K/OTzQzDCfUl3neakV12w+EQyxklAWpiqxjPqea/dA3qDvBWYxQ025oDfUz27p1DEOcdSA2dRzWCXNl1hm+rZCL2PcxTP0B91dBWrN4xOINc0rw5DEKW2wwuNuG9g="

    # MASTER_URL (link to the Python master)
    - secure: "Dr0B1EHYiV3EZvDTTSjwYpkFr1iZKZ5ryq8YAYvshrT+jFSNXvIof4i4ZX5YY2fZOg9nFc41ltjjPxWzc6RVf9hId+h5idFWh+Kfj/7+9TlOyYB0JfUzvOsU1YvGSGUpM5BRWTicAzd4PoXaKnUxIfQbGQ25P185OyW/4nbzNtI="

    # Display
    - DISPLAY=:99.0

before_install:

  # Prepare a Python environment with enpkg installed in it.
  - wget -O master.sh ${MASTER_URL}
  - bash master.sh -bp ./runtime
  - source ./runtime/bin/activate
  - wget https://s3.amazonaws.com/enstaller-assets/enstaller/bootstrap.py
  - python `pwd`/bootstrap.py

  # At this point, enpkg is installed - provide auth info now.
  - echo "EPD_auth = '"${EPD_auth}"'" > ${HOME}/.enstaller4rc

  # Install pip
  - enpkg pip

  # Make sure you have a web browser installed (for the web tests) and the X
  # server is running
  - sudo apt-get update
  - sudo apt-get install firefox
  - sh -e /etc/init.d/xvfb start

install:
  - sh develop.sh

script:
  # Run the tests
  - nosetests -sv

after_script:
  - coverage report

notifications:
  email: false
