language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
env:
  - ETS_TOOLKIT=qt4 QT_API=pyqt DISPLAY=:99.0
before_install:
  - sudo apt-get update
  - sudo apt-get install python-qt4 python-qt4-dev python-sip python-qt4-gl libqt4-scripttools python-numpy firefox
  - sh -e /etc/init.d/xvfb start
install:
  - pip install -r requirements.txt
  - pip install -r dev_requirements.txt
  - python setup.py develop
script:
  - coverage run -m unittest discover
after_script:
  - coverage report