language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

env:
  - DISPLAY=:99.0

before_install:
  # Make sure you have a web browser installed (for the web tests) and the X
  # server is running
  - sudo apt-get update
  - sudo apt-get install firefox
  - sh -e /etc/init.d/xvfb start
  # Install PySide via Ubuntu repos as it is not available on PyPI for linux.
  - sudo apt-get install python-pyside

install:
  - python setup.py install
  # Add the test dependencies
  - pip install nose selenium coverage

script:
  # Run the tests
  - nosetests -sv

after_script:
  - coverage report

notifications:
  email: false
