language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
env:
  - ETS_TOOLKIT=qt4
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install python-qt4 python-qt4-dev python-sip python-qt4-gl libqt4-scripttools
install:
  - pip install -r requirements.txt
  - python -c 'from pyface.qt import QtCore, QtGui'
  - pip install -r dev_requirements.txt
  - python setup.py develop
script:
  - python -m nose.core
