branches:
  only:
    - master

environment:
  python: "C:/Python27-x64"
  EPD_auth:
    secure: ....
  MASTER_URL:
    secure: ....
  BOOTSTRAP_PY_URL:
    secure: ....
  DISPLAY: 99.0

init:
  - ps: $Download-File $Env:MASTER_URL
  -


##### TRAVIS JIGNA BELOW #####

language: python

python:
  - "2.7"

env:
  global:
    # EPD_auth
    - secure: "KY7cnBEpCrBo3VVHeX/XwDta54bhTZHilpWT1RuwtIVLgtaNPMFCOPqM7W4mnWtNV4uXgcGTTsbGjsCm3dFTk0fKdo8gacr9UMHRbX4P6x59LbFPuoAPqoFsUBr3zScqeO913gkihHOqiBk+ULtD3i35kuy4ebNcxFKgPnljSeo="

    # MASTER_URL (link to the Python master)
    - secure: "Dr0B1EHYiV3EZvDTTSjwYpkFr1iZKZ5ryq8YAYvshrT+jFSNXvIof4i4ZX5YY2fZOg9nFc41ltjjPxWzc6RVf9hId+h5idFWh+Kfj/7+9TlOyYB0JfUzvOsU1YvGSGUpM5BRWTicAzd4PoXaKnUxIfQbGQ25P185OyW/4nbzNtI="

    # BOOTSTRAP_PY_URL (link to Enstaller's bootstrap.py file)
    - secure: "E29bCQ4/IYToJAXqYK1aRvOD0NrzVapcIpIh4lLWcJDXNVsVZ3El0ctL9iPag+EI8tVyXidWVBh+1chEgKkOiXdOH8Pks3SviXKzQzARlPv78Uq38JD/G4uyACUlxpSFvMW93aeyekbSOhEQgSOjdoLP7Cgs6uQcFCQq6qNSd/Q="

    # Display
    - DISPLAY=:99.0

before_install:

  # Prepare a Python environment with enpkg installed in it.
  - wget -q -O master.sh ${MASTER_URL}
  - bash master.sh -bp ./runtime
  - source ./runtime/bin/activate
  - wget -q -O bootstrap.py ${BOOTSTRAP_PY_URL}
  - python ./bootstrap.py

  # At this point, enpkg is installed - provide auth info now.
  - echo "EPD_auth = '"${EPD_auth}"'" > ${HOME}/.enstaller4rc

  # Install pip
  - enpkg pip

  # Make sure you have a web browser installed (for the web tests) and the X
  # server is running
  - sudo apt-get update
  - sudo apt-get install firefox
  - sh -e /etc/init.d/xvfb start

install:
  - sh develop.sh

script:
  # Run the tests
  - nosetests -sv

after_script:
  - coverage report

notifications:
  email: false
